return {
	require("plugins.ui"),
	require("plugins.colorscheme"),
	require("plugins.cloak"),
	require("plugins.mason"),
	require("plugins.lsp"),
	require("plugins.prettier"),
	require("plugins.supermaven"),
	require("plugins.typescripttools"),
	require("plugins.harpoon"),
	require("plugins.prettier"),
	require("plugins.editor"),
	require("plugins.undotree"),
	require("plugins.treesitter"),
}
